### ISSUE TITLE
Collapsible tile categories?

### ISSUE THREAD

**Issue by hanskokx** [Zren/plasma-applet-tiledmenu#104]
I want to mimic my Win10 device with collapsible tile categories.  Is this possible? If so, I haven't found a way. (v41)

**Comment by Zren** [comment]
Tile "Folders"? No it's not yet possible as mentioned on https://store.kde.org/p/1160672/ and the ReadMe

**Comment by hanskokx** [comment]
😖 I don't know how I missed that. Dangit.
