### ISSUE TITLE
[FR] Background transparency and blur

### ISSUE THREAD

**Issue by lucidtanooki** [Zren/plasma-applet-tiledmenu#109]
Hi there,

thanks for this great menu plasmoid. Is there a way to set transparency and/or blur for the background. That would be awesome.

Cheers,
Georg

**Comment by Zren** [comment]
The transparency of popup windows is controlled by the Plasma Style. I could hack it to make it 100% transparent or 0% transparent as covered in Issue #44 through a hack that could break at any time.

I cannot control the blur Desktop Effect at all.

**Comment by lucidtanooki** [comment]
I understand. Thank you.
