### ISSUE TITLE
translation for Slovenian language

### ISSUE THREAD

**Issue by Ugowsky** [Zren/plasma-applet-tiledmenu#110]
[Tiled menu.zip](https://github.com/Zren/plasma-applet-tiledmenu/files/6888183/Tiled.menu.zip)
Hy, Zren! This is official Slovenian translation for Tiled menu. Thank you for coding!

Take care,
Ugo Ugowsky

**Comment by Zren** [comment]
Thanks for translating! Hmm. Looks like you used `si.po` but put `"Language: sl\n"` in the file. I needed to rename it to `sl.po` to get it working.

```
	"si_LK:si:Sinhala (Sri Lanka)"
	"sk_SK:sk:Slovak (Slovakia)"
	"sl_SI:sl:Slovenian (Slovenia)"
```

I needed to add `(%1)` to:

```po
#: ../contents/ui/config/ConfigGeneral.qml
msgid "Desktop Theme (%1)"
msgstr "Tema namizja"
```

Subscribe to the pinned "Translation Updates" issue to receive email updates when new messages are added.

**Comment by Ugowsky** [comment]
Oh my ... Sorry for that. Of course it's sl.po, I don't know where was my head. I will be more careful in the future.

Thanks and all the best!
