### ISSUE TITLE
Enter on numpad doesn't work

### ISSUE THREAD

**Issue by keenanweaver** [Zren/plasma-applet-tiledmenu#118]
When searching for something in Tiled Menu, and pressing enter on the numpad to open the searched item, results in nothing happening. Regular enter works fine, but not the numpad enter. Tried several different computers (and keyboards too), but it doesn't register anything. Works as expected on the default Plasma start menu.

OS: Arch Linux x86_64 
Kernel: 5.15.12-arch1-1
DE: Plasma 5.23.5 
WM: KWin
X11
Tiled Menu v43 (also happens on v42)

Any tips or guidance is appreciated! Love this menu.

**Comment by Zren** [comment]
* https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/SearchField.qml#L93
* `if (event.key == Qt.Key_Return)`
* https://doc.qt.io/qt-5/qt.html#Key-enum
