### ISSUE TITLE
Icon in Control Bar is extremely small

### ISSUE THREAD

**Issue by JPRuehmann** [Zren/plasma-applet-tiledmenu#14]
Hello
I love this Starter.
But how can I make my custom control bar Icon bigger?
with other Launchers it works fine.
Thanks.

**Comment by Zren** [comment]
Either uncheck "Fixed Size"

![](https://i.imgur.com/GhH9Gtz.png)

or change the Panel Icon Size Hint in the System Settings.

![](https://i.imgur.com/8Xwsoa9.png)

**Comment by JPRuehmann** [comment]
Sorry, either the Setting is not available and the Systemmsetting is 48Pixel, All othe Icons are sized correctly.
I am using Plasma 1.8.9 and Tiled Menu v11.
since newer Versions not working.

**Comment by Zren** [comment]
> Tiled Menu v11

There's the reason why. I only added support for following the panel icon hint in v17.

> v17 - September 13 2017 9 months ago

> * Used a fixed panel icon by default, using the same icon size as the other icons in the panel.

You could play around with `~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/Main.qml`.

The file has a `compactRepresentation` which is the panel icon.

![](https://i.imgur.com/dkQl9yS.png)

Try changing `Layout.preferredWidth` or `Layout.preferredHeight` to `Layout.preferredWidth: 48`.

You test your changes by restarting plasmashell with `killall plasmashell; kstart5 plasmashell`

**Comment by JPRuehmann** [comment]
Wrong Spot, right Tip Thanks.
Change "readonly property int panelIconSize: 24 * units.devicePixelRatio" to "readonly property int panelIconSize: 48 * units.devicePixelRatio" in "~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/AppletConfig.qml" did the Trick.
Is there a way to automaticaly set the Size from the System Settings?

**Comment by Zren** [comment]
I don't remember which version of Plasma added the "panel hinting" for Plasma 5. The option in System Settings existed beforehand (legacy from Plasma 4) but wasn't being used.

The variable you're looking for is `units.iconSizeHints.panel`. No idea if it works in Plasma 5.8.x

The Application Launcher uses this complicated code now.

* https://github.com/KDE/plasma-desktop/blob/master/applets/kickoff/package/contents/ui/Kickoff.qml#L36-L74

I used an older version of Application Launchers code in Tiled Menu v17, and it looks like this:

* https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/LauncherIcon.qml#L9-L49

**Comment by JPRuehmann** [comment]
The Variable works.
Thanks
