### ISSUE TITLE
[Feature]: support run commands in start page pins

### ISSUE THREAD

**Issue by alr86** [Zren/plasma-applet-tiledmenu#155]
I tried to run these commands(in the URL field) in pined tiles but they are not working:
`xfce4-terminal --command="waydroid show-full-ui" -T "Waydroid Runner"`
`file:///home/alr86/Applications/waydroidRunner.sh`
`gamemoderun /home/alr86/Applications/waydroidRunner.sh`

with the second command, the start menu was hiding but nothing happened.

**Comment by Zren** [comment]
You need to create an application launcher in your start menu with `kmenuedit` (aka Edit Applications). Then you can pin the new application shortcut to the tile grid.
