### ISSUE TITLE
Error loading QML file

### ISSUE THREAD

**Issue by douglasg14b** [Zren/plasma-applet-tiledmenu#3]
Trying to install v19 on Plasma 5.12.4, receive the following error when I go to launch the menu:

> Error loading QML file: file:///home/douglas/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/Main.qml:23:2: Type AppsModel unavailable
> file:///home/douglas/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/AppsModel.qml:29:3: Cannot assign to non-existent property "showAllSubtree"

Any idea how I can fix this?

**Comment by Zren** [comment]
You installed and older version first didn't you? You'll need to restart plasmashell for it to recognize a different version.

Restart either by logging off or running the following command:

`killall plasmashell; kstart5 plasmashell`

**Comment by Zren** [comment]
Not sure why, but it's loading an older version instead of the current version. Deleting `~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/` then reinstalling the widget should work.

The above is for anyone else who encounters the issue.
