### ISSUE TITLE
Initial Indonesia translation

### ISSUE THREAD

**Issue by ardumpl** [Zren/plasma-applet-tiledmenu#34]
Hi, this is my initial Indonesia translated file. Here for pot file. for further time i will re-edit the file since I still not found equivalent meaning for few strings.
[id_ID.tar.gz](https://github.com/Zren/plasma-applet-tiledmenu/files/2798479/id_ID.tar.gz)

**Comment by Zren** [comment]
Awesome! Thanks for the translations. I gave you credit in the commit.

I renamed it to `id.po` and put it here:  
https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/translate/id.po

You can just put the changed translations in a comment here like if you'd like.

```
msgid "Example"
msgstr ""
```

**Comment by Zren** [comment]
I just added two more messages in preparation for v28. With "Import/Export Layout", the user can sort of infer that we're talking about the grid, but should I change it to "Import/Export Tile Layout" or "Import/Export Tiles"?

Added Keys:
```
"Import/Export Layout"
"Tiles Only"
```

**Comment by ardumpl** [comment]
Wow, that was fast respond! I will check it
