### ISSUE TITLE
Re-edit Indonesian translation

### ISSUE THREAD

**Issue by ardumpl** [Zren/plasma-applet-tiledmenu#35]
I have been checked and edited some ambigious translation for some strings. Here for re-edit translation
[id.zip](https://github.com/Zren/plasma-applet-tiledmenu/files/2799959/id.zip)

**Comment by Zren** [comment]
Alright! There's 3 messages left, then I can release v28.

```
#: ../contents/ui/SearchField.qml:21
msgid "Search Bookmarks"
msgstr "Cari Penanda"

#: ../contents/ui/SearchField.qml:23
msgctxt "Search [krunnerName, krunnerName, ...], "
msgid "Search %1"
msgstr ""
```

`msgstr "Cari %1"` should work there.

```
msgid "Default"
msgstr ""
```

* https://translate.google.com/#view=home&op=translate&sl=en&tl=id&text=Default

mentions the translation is "Default", which I think is for "default option". Completely forgot the word is also used for "defaulted on a loan".


```
msgid "Tiles Only"
msgstr ""
```

* `tiles only` => `ubin saja` https://translate.google.com/#view=home&op=translate&sl=en&tl=id&text=tiles%20only
* `only tiles` => `hanya ubin` https://translate.google.com/#view=home&op=translate&sl=en&tl=id&text=only%20tiles

So I'm guessing `msgstr "Ubin saja"`?

**Comment by ardumpl** [comment]
The word ubin saja is correct one.  But i decided to add any word to make it more clearly such as "Tampilkan ubin saja". is mean show tiles only

For "default" strings phrase, I dont make any change. So i ignore it

**Comment by ardumpl** [comment]
[id.zip](https://github.com/Zren/plasma-applet-tiledmenu/files/2801255/id.zip)
It's done!!... I have been filled the blank strings. Go ahead @Zren

**Comment by Zren** [comment]
Ah, I filled it out based on your comment, heh.

I'll release v28 tomorrow night, giving the release a final bit of testing.
