### ISSUE TITLE
breeze plasmatheme, searchbox visible with "tiles only" option

### ISSUE THREAD

**Issue by brudolp** [Zren/plasma-applet-tiledmenu#40]
black line next to power button is the border of the input field

https://i.imgur.com/OnfanYe.png

**Comment by Zren** [comment]
Ah, it appears that it's trying to draw the searchbox 0px width. It's outside the other thing so it's not hidden.

We just need to add

https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/SearchView.qml#L220-L221

```qml
visible: opacity > 0
opacity: config.showSearch ? 1 : 0
```

to the SearchField

**Comment by Zren** [comment]
Fixed in v29
