### ISSUE TITLE
[Request] opaque Menu with transparent tiles

### ISSUE THREAD

**Issue by brudolp** [Zren/plasma-applet-tiledmenu#43]
https://i.imgur.com/ZotwqQA.png
something like this :)

**Comment by Zren** [comment]
Impossible without a major refactor tbh. While it would be neat eyecandy, it would be annoying to maintain.

* You'd need to have a "custom" `Plasma.Dialog` you could manipulate to hide the popup's background. I've done this before for other widgets but it's more of a hack than anything.
    * https://github.com/KDE/plasma-framework/blob/master/src/plasmaquick/dialog.h#L141-L146
* Then you'd draw a opache `Rectangle` for the background, but you'd mask that Rectangle based on the tile grid. You'd have to monitor the grid for changes.
    * https://doc.qt.io/qt-5/qml-qtquick-rectangle.html
    * https://doc.qt.io/qt-5/qml-qtgraphicaleffects-opacitymask.html
* There's no guarantee that after implementing it, the "masking effect" will run at 60fps. It might be rather "laggy" like the current outline hover effect which also uses `OpacityMask`. So you might need to spend time optimizing it. There's a good change you won't be able to optimize it either, at least not without a dedicated C++ QML plugin.

If a widget was able to access the desktop wallpaper, you could maybe "trick it" by cropping that section of the wallpaper and drawing that as the tile's background. You could probably do that trick manually atm, but it would be tedious.

**Comment by brudolp** [comment]
maybe using your breeze alpha black theme, setting it to fully transparent and drawing a custom background excluding the tiles?
