### ISSUE TITLE
[Suggestion] Make it an official Plasma widget

### ISSUE THREAD

**Issue by Khyber3737** [Zren/plasma-applet-tiledmenu#48]
I really like your Plasmoid, the amount of options is great.

Is there any reason why this isn't shipped by default with Plasma? So you could select this widget in the _Show Alternatives_ option.

It's by far the most complete and that can be punched until it fits most use cases.

**Comment by digitalethics** [comment]
I second this. It's time this is scheduled for inclusion if not made the new default Plasma setting. Are you involved with Plasma development on Phabricator and has there been a request made? I had a thorough look at your widget, filed four remaining issues, but I think this is ready for prime time. Fantastic work!
