### ISSUE TITLE
Alt + Right Click doesn't seem to work

### ISSUE THREAD

**Issue by sTiKyt** [Zren/plasma-applet-tiledmenu#57]
Can't resize my tiles menu
There probably should be some custom way to change size? Without mouse..

**Comment by Zren** [comment]
You can adjust the number of column in the config, but I never got around to adding a height control there.

Perhaps your distro uses `Meta+RightClick`? Check System Settings > Window Management > Window Behaviour > Window Actions tab > Inner Window, Titlebar and Frame Actions section > Modfier Key. The Modifier key usually defaults to `Alt`, but I usually change it to `Meta` so it doesn't conflict with Dota2.

You can go to the Import/Export tab in TiledMenu's config, then edit `"popupHeight": 620,` to whatever height you want.

**Comment by sTiKyt** [comment]
My "Right Click" was set to "Do Nothing"... 
Thanks @Zren
