### ISSUE TITLE
[Suggestion] Increase number of rows

### ISSUE THREAD

**Issue by FoxyBit** [Zren/plasma-applet-tiledmenu#64]
Hi, love this menu.

What would be great is as well as being able to increase the number of columns, is to increase the number of rows. Having a maximum of 10 is not enough for me, but I don't want to go full screen.

Thanks.

**Comment by Zren** [comment]
`Alt+RightClick+Drag` to resize the popup. The tooltip already exists to tell you this, but there will be 2 more things to make this more discoverable in the next version:


![2020-06-08___18-17-18](https://user-images.githubusercontent.com/416367/84085765-4c727b80-a9b4-11ea-80ff-703f03173004.png)

**Comment by FoxyBit** [comment]
Thanks for the quick reply.

It didn't even occur to me to just hover over a blank area of the menu. Worked perfectly. Thanks again :)
