### ISSUE TITLE
option to remove icon? 

### ISSUE THREAD

**Issue by tjw0lf** [Zren/plasma-applet-tiledmenu#68]
I installed a game from lutris. It was custom game from gog games. I had to remove the installed game doing some testing i had bad ram stick and fixed it. After removing files there are no files anymore for the game! It left game icon in the menu and i do not know how to get rid of it if you can help me please. Thank you

**Comment by Zren** [comment]
Right click the tile > Unpin

**Comment by tjw0lf** [comment]
There's no option like that to remove icon. I think i may i found where its located where lutris put it at

<a href="https://imgur.com/7BUDXMD"><img src="https://i.imgur.com/7BUDXMD.png" title="source: imgur.com" /></a>

**Comment by Zren** [comment]
Oh, the app is still in the app list? Right click the panel icon, Menu Editor (or run `kmenuedit`). This is a gui that modifies the `.desktop` files in `~/.local/share/applications/`. You can override the name/command of the `.desktop` files in `/usr/share/applications/` installed by your package manager.

Lutris probably created a `.desktop` file in  `~/.local/share/applications/`.

If you manually edit `~/.local/share/applications/`, you need to run `kbuildsycoca5` to tell KDE files have been changed and to reload them.

**Comment by tjw0lf** [comment]
OK Thank you 

I just removed those icons, And restarted but they where still there. I run kbuildsycoca5 in terminal and it got rid of them. Looks like it doesn't run on startup. I'm running Kubuntu 20.04. 

I will have to put it in autostart to run kbuildsycoca5.

Thanks

**Comment by tjw0lf** [comment]
Thanks for your very fast reply. problem fixed now.
