### ISSUE TITLE
Plasmoid window keeps getting shorter

### ISSUE THREAD

**Issue by Zzombiee2361** [Zren/plasma-applet-tiledmenu#71]
Over time, the widget height is getting shorter. Every 2-3 days I have to manually increase the height again. It can be visibly observed when configuration is open
![output](https://user-images.githubusercontent.com/37852137/85251709-366cbc80-b484-11ea-928b-2e4945fe87e5.gif)

**Comment by Zren** [comment]
I find this incredibly funny. It's slowly shrinking!

I'm guessing you have non-default dpi? Or non-default monitor scaling?

* https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/Main.qml#L152-L166
* https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/AppletConfig.qml#L63-L69

Basically, the code notices the window height has been changed, then devides by the dpi and stores the "size without dpi scaling" to disk.

```
plasmoid.configuration.popupHeight = height / units.devicePixelRatio
```

And when it notices the config changes, it multiplies by the dpi to scale it back up.

```
popupHeight = plasmoid.configuration.popupHeight * units.devicePixelRatio
```

It would be good to know what the value of `units.devicePixelRatio` is.

Also, I guess I should... `Math.round(height / units.devicePixelRatio)`? Right now it's probably using `Math.floor()` when converting a floating point Real number to an Integer.

**Comment by Zren** [comment]
If you edit `~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/Main.qml` then change:

```
plasmoid.configuration.popupHeight = height / units.devicePixelRatio
```

to:

```
plasmoid.configuration.popupHeight = Math.round(height / units.devicePixelRatio)
```

Then restart. Open TiledMenu's config and edit the height. Does the bug go away?

**Comment by Zzombiee2361** [comment]
> I'm guessing you have non-default dpi? Or non-default monitor scaling?

Nope, I have 1366x768 resolution with no custom display configuration whatsoever.

> If you edit `~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/Main.qml`

Ok lemme try that real quick... Oh god oh f*ck it's sinking even faster now. On a serious note, using `Math.ceil` instead fixes the problem.

**Comment by Zren** [comment]
> Oh god oh f*ck it's sinking even faster now.

Lol.

And nicely done with thinking of using `Math.ceil`. Hmm. That means the pattern is 50.4, 49.4, 48.4, ... I thought the pattern might be 50.9, 49.9, 48.9, ... which is why I suggested `Math.round`.

So you have a screen smaller than 1080p. Makes sense, as you're probably under 96dpi. So I assume `units.devicePixelRatio` is less than `1.0`.

Mind doing another edit? You won't need to restart (just open and close the config window).

Edit `contents/ui/config/ConfigGeneral.qml` and change:

```
	ConfigSection {
		label: i18n("Popup") + ' ' + units.devicePixelRatio
```
It'll show the value of `units.devicePixelRatio` (what we divide the popup height by) in the config window like:

![2020-06-23___00-02-17](https://user-images.githubusercontent.com/416367/85359633-d0645180-b4e4-11ea-8664-be8e27bb36d3.png)

**Comment by Zzombiee2361** [comment]
Hmm.. It's not less than 1, but it's barely above it

![image](https://user-images.githubusercontent.com/37852137/85366672-0a1f7180-b552-11ea-9bf2-d248d6dbca30.png)

**Comment by Zren** [comment]
You're right, `Math.round()` when setting did make it worse!

```
qml: set dpr=1.0011657433056327 h1=619.278080723072 h2=619
qml: get dpr=1.0011657433056327 h1=619.7215951061867
qml: set dpr=1.0011657433056327 h1=618.2792451090025 h2=618
qml: get dpr=1.0011657433056327 h1=618.720429362881
qml: set dpr=1.0011657433056327 h1=617.2804094949331 h2=617
qml: get dpr=1.0011657433056327 h1=617.7192636195754
qml: set dpr=1.0011657433056327 h1=616.2815738808636 h2=616
qml: get dpr=1.0011657433056327 h1=616.7180978762698
qml: set dpr=1.0011657433056327 h1=615.2827382667941 h2=615
qml: get dpr=1.0011657433056327 h1=615.7169321329641
qml: set dpr=1.0011657433056327 h1=614.2839026527247 h2=614
qml: get dpr=1.0011657433056327 h1=614.7157663896585
qml: set dpr=1.0011657433056327 h1=613.2850670386551 h2=613
qml: get dpr=1.0011657433056327 h1=613.7146006463528
qml: set dpr=1.0011657433056327 h1=612.2862314245857 h2=612
qml: get dpr=1.0011657433056327 h1=612.7134349030472
qml: set dpr=1.0011657433056327 h1=611.2873958105163 h2=611
qml: get dpr=1.0011657433056327 h1=611.7122691597416
qml: set dpr=1.0011657433056327 h1=610.2885601964468 h2=610
qml: get dpr=1.0011657433056327 h1=610.7111034164359
```

Even if I `Math.round()` when reading, it still doesn't help.

```
qml: set dpr=1.0011657433056327 h1=619.278080723072 h2=619
qml: get dpr=1.0011657433056327 h1=619.7215951061867 h2=620
qml: set dpr=1.0011657433056327 h1=618.2792451090025 h2=618
qml: get dpr=1.0011657433056327 h1=618.720429362881 h2=619
qml: set dpr=1.0011657433056327 h1=617.2804094949331 h2=617
qml: get dpr=1.0011657433056327 h1=617.7192636195754 h2=618
qml: set dpr=1.0011657433056327 h1=616.2815738808636 h2=616
qml: get dpr=1.0011657433056327 h1=616.7180978762698 h2=617
qml: set dpr=1.0011657433056327 h1=615.2827382667941 h2=615
```

When we use `Math.ceil` when setting like you mention, and the implicit `Math.floor` when casting real => int when getting it looks like this:

```
qml: set dpr=1.0011657433056327 h1=619.278080723072 h2=620
# Resized
qml: set dpr=1.0011657433056327 h1=603.2967108979605 h2=604
qml: get dpr=1.0011657433056327 h1=604.7041089566021 h2=604
# Resized
qml: set dpr=1.0011657433056327 h1=678.2093819531708 h2=679
qml: get dpr=1.0011657433056327 h1=679.7915397045246 h2=679
# Resized
qml: set dpr=1.0011657433056327 h1=690.1954093220045 h2=691
qml: get dpr=1.0011657433056327 h1=691.8055286241922 h2=691
```

And if we `Math.ceil` both, it seems to grow 1px from whats read in the config, but doesn't grow bigger in a loop as it settles there.

qml: set dpr=1.0011657433056327 h1=619.278080723072 h2=620
# Resize
qml: set dpr=1.0011657433056327 h1=674.214039496893 h2=675
qml: get dpr=1.0011657433056327 h1=675.7868767313021 h2=676
# Resize
qml: set dpr=1.0011657433056327 h1=653.238491601434 h2=654
qml: get dpr=1.0011657433056327 h1=654.7623961218837 h2=655
# Resize
qml: set dpr=1.0011657433056327 h1=700.1837654626992 h2=701
qml: get dpr=1.0011657433056327 h1=701.8171860572485 h2=702
# Resize
qml: set dpr=1.0011657433056327 h1=559.3479438789037 h2=560
qml: get dpr=1.0011657433056327 h1=560.6528162511543 h2=561
```

I tried testing devicePixelRatio of `2.0011657433056327` and it seems to hold up fine.

```
qml: pH.get dPR=2.001165743305633 pH3=620 pH4=1240.7227608494925 pH5=1240
# Resized when opening as my screen is only 1080px tall
qml: pH.set dPR=2.001165743305633 pH1=1038 pH2=518.6976658342032 pH3=519
qml: pH.get dPR=2.001165743305633 pH3=519 pH4=1038.6050207756234 pH5=1038
```

**Comment by Zzombiee2361** [comment]
What about rounding `units.devicePixelRatio`? Would it cause another problem?

**Comment by Zren** [comment]
If I round the ratio, then the widget wouldn't support 125%, 150%, 175% scaling.

**Comment by Zzombiee2361** [comment]
Then only keep the first 2 digit of the ratio, would there be any reason to have more precision? If there's more problem then just use `Math.ceil`.
