### ISSUE TITLE
[Advanced] Install KDE Plasma menu in gnome

### ISSUE THREAD

**Issue by azrea** [Zren/plasma-applet-tiledmenu#86]
Is there way to install only kde plasma menu in gnome and apply themes? There's a minimum possible way to install 'apt install kde-plasma-desktop` but it still whole desktop environment then it replace settings menus and install many other applications

Again i'm asking if there any way to install as `apt install dolphin` or other tricks?

However i aware about arc menu and dash to panel extensions.

**Comment by Zren** [comment]
It's possible to use `latte-dock`, but it probably installs a ton of packages. No idea if anyone's used it in Gnome before.

Gnome extensions use JavaScript. Plasma using QML. It can't really be used as a "gnome widget". Unless the gnome widget launched a separate `plasmawindowed`-like process/window in the background, and only displayed it via dbus when you click the gnome widget to toggle it into view. You wouldn't be able to spawn a new process each time as Tiled Menu takes a second to load, which is too slow for an app launcher response time.

**Comment by azrea** [comment]
@Zren thank you. i guess that's why kubuntu available.
