### ISSUE TITLE
Background Colour

### ISSUE THREAD

**Issue by MeoliNasa** [Zren/plasma-applet-tiledmenu#90]
While i've been able to change both theme and Kvantum background colour to one of my likeness, i cant figure out where Tiled Menu picks its general background colour. I've been able to change only the sidebar colour  (changing theme.button.background) but it will be nice to be able to change all the background colour in the setting menu (even Win10 lets you do that). In the meantime, i will appreciate a lot if you can point me to the right config to edit the general background colour. 
And thanks for the great work!

**Comment by Zren** [comment]
Oh, it's because I don't use the standard `GroupBox` since Breeze's is pretty ugly (centered titles). Edit `lib/ConfigSection.qml` where it sets:

```
	color: "#0c000000"
	border.width: 2 * units.devicePixelRatio
	border.color: "#10000000"
```

**Comment by MeoliNasa** [comment]
Solved, thanks <3
