### ISSUE TITLE
The RTL interface needs finnishing touches

### ISSUE THREAD

**Issue by omeritzics** [Zren/plasma-applet-tiledmenu#92]
Hello, some of the text in the RTL interfaces are aligned to left, and they should be aligned to right.

Present:
![Settings](https://user-images.githubusercontent.com/66558205/114940226-2d513f80-9e4a-11eb-996c-db1c29a1aea4.png)
(the version text is still aligned to left)

Expected:
![expected-settings](https://user-images.githubusercontent.com/66558205/114940304-4c4fd180-9e4a-11eb-8b28-3e4f99803bf4.png)

_Note: There are new RTL problems, I'll list them later._

**Comment by Zren** [comment]
If you can help me list all the places, it would be helpful.

* [ ] Popup
  * [ ] TileGrid splash list text
  * [ ] TileGrid group labels
  * [ ] Tile labels should default to the right?
    * I might remove the "Right Align" option, leaving Left or Center aligned labels. "Left" would automatically switch to "Right" aligned when in a mirrored locale.
  * [ ] Sidebar should be on right? Eg: TileGrid | SearchView | Sidebar
    * [ ] Sidebar tooltips
  * [ ] Sidebar submenus need to be mirrored
  * [ ] App List needs to be mirrored
* [ ] Config
  * [ ] `ConfigIcon.qml` TextField needs to be mirrored
  * [ ] `ConfigColor.qml` TextField needs to be mirrored
* [ ] TileEditor
  * [ ] TileEditor GroupBox labels + checkboxes
  * [ ] TileEditor Icon/Image browse buttons need to more to the left
  * [x] Tile size grid is probably okay as is? Or does it need to be mirrored?

**Comment by omeritzics** [comment]
The "Search" text is aligned to left
![search](https://user-images.githubusercontent.com/66558205/97992633-9e94bd00-1deb-11eb-981b-adb47f12bf3b.png)
and the "Version: %1" text
![version](https://user-images.githubusercontent.com/66558205/97993174-5e820a00-1dec-11eb-9227-ab450033a91a.png

**Comment by Zren** [comment]
* "Version: 41" should not be mirrored to "41 :Version"?
* In your screenshot, it looks like the AppList is already mirrored?

**Comment by omeritzics** [comment]
>     * "Version: 41" should not be mirrored to "41 :Version"?
The text mirroring is correct, but not the align. The "Version: 41" text should be under the "General" (כללי) text.
>     * In your screenshot, it looks like the AppList is already mirrored?
The same thing here, the "Search" string is aligned to left and not to right (the align while typing is correct, but it isn't correct when the search box is empty).
