### ISSUE TITLE
[feature request/ ui] search bar follow theme 

### ISSUE THREAD

**Issue by Taza53** [Zren/plasma-applet-tiledmenu#99]
The search bar looks out of place. in dark and transparent theme(layan).
so can it be more integrated to the theme or a separate option to change the colour/transparency of the search bar. The first option seems better to me.

**Comment by Zren** [comment]
It already has a toggle to make it follow the theme in the desktop theme in the settings. I guess I should rename the label to "Plasma Style" though.

**Comment by Taza53** [comment]
okay thanks found the settings.
for anyone who cant find them, right-click on the application launcher(tiledmenu). Then press config **Tiled menu** you can find all the options there.
